import "server-only";
import type { StoredEvent } from "./event-store";

export function toEventDto(event: StoredEvent & { distanceMiles?: number }, options: { detail?: boolean } = {}) {
  return {
    id: event.id,
    title: event.title,
    normalizedTitle: event.normalizedTitle,
    description: options.detail ? event.description : undefined,
    shortSummary: event.shortSummary,
    sourceName: event.sourceName,
    sourceUrl: event.sourceUrl,
    originalEventUrl: event.originalEventUrl,
    imageUrl: event.imageUrl,
    startDateTime: event.startDateTime,
    endDateTime: event.endDateTime,
    timezone: event.timezone,
    venueName: event.venueName,
    address: options.detail ? event.address : undefined,
    neighborhood: event.neighborhood,
    city: event.city,
    state: event.state,
    postalCode: options.detail ? event.postalCode : undefined,
    latitude: event.latitude,
    longitude: event.longitude,
    distanceMiles: event.distanceMiles,
    locationQuality: event.locationQuality,
    organizerName: event.organizerName,
    organizerType: event.organizerType,
    registrationRequired: event.registrationRequired,
    registrationUrl: event.registrationUrl,
    priceText: event.priceText,
    isFree: event.isFree,
    freeConfidence: event.freeConfidence,
    freeExplanation: event.freeExplanation,
    freebieType: event.freebieType,
    freebieTypes: event.freebieType,
    freebieDescription: event.freebieDescription,
    freebieAvailability: event.freebieAvailability,
    freebieConfidence: event.freebieConfidence,
    celebrityNames: event.celebrityNames,
    celebrityConfidence: event.celebrityConfidence,
    celebrityLabel: event.celebrityLabel,
    notablePeople: options.detail ? event.notablePeople : undefined,
    companyNames: event.companyNames,
    companyConfidence: event.companyConfidence,
    companyInvolvement: options.detail ? event.companyInvolvement : undefined,
    eventCategories: event.eventCategories,
    ageRestriction: event.ageRestriction,
    attendanceFormat: event.attendanceFormat,
    environment: event.environment,
    indoorOutdoor: event.environment,
    familyFriendly: event.familyFriendly,
    capacityLimited: event.capacityLimited,
    status: event.status.toUpperCase(),
    firstSeenAt: event.firstSeenAt,
    lastSeenAt: event.lastSeenAt,
    scrapedAt: event.scrapedAt,
    updatedAt: event.updatedAt,
    sourceReliability: event.sourceReliability,
    overallScore: event.overallScore,
    rankingReasons: event.rankingExplanation,
    rankingExplanation: event.rankingExplanation,
    classificationEvidence: event.evidence,
    evidence: event.evidence,
    sourceLinks: event.sourceLinks.map((source) => ({ name: source.sourceName, sourceName: source.sourceName, url: source.url, isPrimary: source.isPrimary, reliability: source.reliability })),
    isSeed: event.isSeed,
    seedLabel: event.seedLabel,
  };
}
